[tool.poetry]
name = "machining_tools_identification"
version = "0.1.0"
description = "Machining Tool Indentification utilizing Temporal 3D Point Clouds"
authors = ["Thanasis Zoumpekas <thanasis.zoumpekas@ub.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
certifi = "2022.12.7"
charset-normalizer = "2.1.1"
click = "8.1.3"
contourpy = "1.0.6"
cycler = "0.11.0"
docker-pycreds = "0.4.0"
fonttools = "4.38.0"
gitdb = "4.0.9"
GitPython = "3.1.30"
idna = "3.4"
kiwisolver = "1.4.4"
matplotlib = "3.6.2"
numpy = "1.23.5"
packaging = "21.3"
pathtools = "0.1.2"
Pillow = "9.3.0"
promise = "2.3"
protobuf = "4.21.9"
psutil = "5.9.4"
pyparsing = "3.0.9"
python-dateutil = "2.8.2"
PyYAML = "6.0"
requests = "2.28.1"
sentry-sdk = "1.14.0"
setproctitle = "1.3.2"
shortuuid = "1.0.11"
six = "1.16.0"
smmap = "5.0.0"
torchsummary = "1.5.1"
tqdm = "4.64.1"
typing-extensions = "4.4.0"
urllib3 = "1.26.12"
wandb = "0.13.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
